global using RentedArraySharp;
global using System.Collections;
global using GradientDescentSharp;
global using GradientDescentSharp.Utils;
global using GradientDescentSharp.DataAccessors;
global using GradientDescentSharp.GradientDescents;
global using GradientDescentSharp.ComplexDataStructures;
global using GradientDescentSharp.NeuralNetwork.WeightInitializers;
global using GradientDescentSharp.NeuralNetwork.ActivationFunction;
global using Playground;
using System.Diagnostics;
using MathNet.Numerics.LinearAlgebra.Single;
